name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11']
    name: Testing jira-resolver with python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install and configure poetry
        run: pip install poetry && poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install

      - name: Lint with flake8
        run: flake8

      - name: Run static type analyzer
        run: mypy

      - name: Run bandit 
        run: bandit -r -c pyproject.toml